version: '3.9'

services:
###> doctrine/doctrine-bundle ###
  database-test:
    container_name: postgres-test
    image: postgres:13.3-alpine
    environment:
      #POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      #POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    #volumes:
      #- database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      #- ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

#volumes:
###> doctrine/doctrine-bundle ###
  #database_data:
###< doctrine/doctrine-bundle ###
